org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
hermesEnabled=true
newArchEnabled=false
android.suppressUnsupportedCompileSdk=35

MYAPP_RELEASE_STORE_FILE=my-release-key.keystore
MYAPP_RELEASE_KEY_ALIAS=my-key-alias
MYAPP_RELEASE_STORE_PASSWORD=neevios
MYAPP_RELEASE_KEY_PASSWORD=neevios

